### ISSUE TITLE
Create UI/UX section 6

### ISSUE THREAD

**Issue by pum-nfq** [pum-khoa/portfolio#1]
Can you code UI like this?

![Screenshot from 2022-05-10 12-39-59](https://user-images.githubusercontent.com/104960618/167556043-95f4a398-ff87-4a11-a3fc-9981d6d9c7a0.png)

I wanna user can scroll this like a slide to left and right.

Do anything you can (tool, library,...)

Coding at : `index.html` and create css like `src/styles/section-6.css`

```html
<!-- Section 6 -> -->
<section class="section"></section>
<!-- <- Section 6 -->
```

**Comment by thangduongnfq** [comment]
i think i can do it ,can u i assign for me

**Comment by pum-nfq** [comment]
> i think i can do it ,can u i assign for me

Here you are!!
