### ISSUE TITLE
Create UI/UX section 7

### ISSUE THREAD

**Issue by pum-nfq** [pum-khoa/portfolio#2]
Help me create this:
![Peek 2022-05-10 13-32](https://user-images.githubusercontent.com/104960618/167563773-22a9cecb-7829-4ac7-8a3e-1bb449ed3c34.gif)

Do anything you can (tool, library,...)

Coding at : `index.html` and create css like `src/styles/section-7.css`

index.html
```html
<!-- Section 7 -> -->
<section class="section"></section>
<!-- <- Section 7 -->
```

**Comment by nguyendangnfq** [comment]
let me do it !!!

**Comment by pum-nfq** [comment]
here u r!
